---

docker_config:

  master_passwd: "{{ config.master_passwd }}"
  internet_domain: "{{ config.internet_domain }}"

  daemon:
    "log-driver": "json-file"
    "log-opts":
      "max-size": "1g"
      "max-file": "3"
      "compress": "true"

  projects:
    privcore:
      definition:
        version: '2'
        services:
          libreoffice-online:
            container_name: 'collabora'
            image: 'collabora/code'
            restart: unless-stopped
            ports:
              - 9980:9980
            environment:
#              - 'domain={{ config.internet_domain.split(".")|join("\\.") }}'
              - 'aliasgroup1=https://{{ config.internet_domain }}:443'
              - 'server_name={{ config.internet_domain }}'
              - 'username=admin'
              - 'password={{ config.master_passwd }}'
              - 'DONT_GEN_SSL_CERT=1'
              - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true'
#              - 'SLEEPFORDEBUGGER=0'
            cap_add:
              - MKNOD

