---

nextcloud_config:
  suffix: "{{ config.suffix }}"

  internet_domain: "{{ config.internet_domain }}"
  smtp_internet_domains: "{[ config.smtp_internet_domains }}"

  country_code: "{{ config.country_code }}"

  tls_ca_cert: "{{ config.tls_ca_cert }}"
  tls_cert: "{{ config.tls_cert }}"
  tls_cert_key: "{{ config.tls_cert_key }}"

  admin_user: "{{ config.admin_user }}"

  master_passwd: "{{ config.master_passwd }}"

  ro_user_dn: "{{ config.ro_user_dn }}"
  ro_user_pw: "{{ config.ro_user_passwd }}"

  mysql_user: nextcloud
  mysql_pass: "{{ lookup('password', '.pc_nc_mysql_passwd chars=ascii_letters,digits,hexdigits length=20') }}"
  mysql_db: nextcloud

  install_dir: /var/www
  version: '29.0.0'
  archive_checksum: 'sha256:e9b53f6432b6f664487d3869645fa121a64cf0ed6aee83aa560903daf86b52bd'

  apps_list:
    - "user_ldap"
    - "calendar"
    - "contacts"
    - "mail"
    - "files_external"
    - "spreed"
    - "theming"
    - "richdocuments" # Collabora online

  apps_config:
    - { app: "richdocuments", key: "public_wopi_url", value: "https://{{config.internet_domain}}" }
    - { app: "richdocuments", key: "wopi_url", value: "https://{{config.internet_domain}}/" }
    - { app: "files_external", key: "user_mounting_backends", value: 'ftp,dav,owncloud,sftp,amazons3,swift,smb,\OC\Files\Storage\SFTP_Key,\OC\Files\Storage\SMB_OC' }


# Example ldap_user config
# $ php occ ldap:create-empty-config --only-print-prefix
# s01
# $ php occ ldap:set-config s01 <key> <value>
#  app_user_ldap_config:
#    - { key: "ldapAgentName", value: '{{ config.ro_user_dn }}' }
#    - { key: "ldapAgentPassword", value: '{{ config.ro_user_passwd }}' }
#    - { key: "ldapBase", value: '{{ config.suffix }}' }
#    - { key: "ldapBaseGroups", value: 'ou=groups,{{ config.suffix }}' }
#    - { key: "ldapBaseUsers", value: 'ou=accounts,ou=users,{{ config.suffix }}' }
#    - { key: "ldapEmailAttribute", value: 'mail' }
#    - { key: "ldapExpertUUIDGroupAttr", value: 'entryUUID' }
#    - { key: "ldapExpertUUIDUserAttr", value: 'entryUUID' }
#    - { key: "ldapGroupFilter", value: '(|(objectclass=posixGroup))' }
#    - { key: "ldapGroupFilterObjectclass", value: 'posixGroup' }
#    - { key: "ldapGroupMemberAssocAttr", value: 'memberUid' }
#    - { key: "ldapLoginFilter", value: '(&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))' }
#    - { key: "ldapLoginFilterEmail", value: '1' }
#    - { key: "ldapLoginFilterUsername", value: '1' }
#    - { key: "ldapHost", value: 'localhost' }
#    - { key: "ldapPort", value: '389' }
#    - { key: "ldapTLS", value: '0' }
#    - { key: "turnOffCertCheck", value: '0' }
#    - { key: "ldapUserDisplayName", value: 'cn' }
#    - { key: "ldapUserDisplayName2", value: 'mail' }
#    - { key: "ldapUserFilter", value: '(|(objectclass=inetOrgPerson))' }
#    - { key: "ldapUserFilterObjectclass", value: 'inetOrgPerson' }
#    - { key: "turnOnPasswordChange", value: '1' }
#    - { key: "ldapConfigurationActive", value: '1' }
#
