---

nextcloud_config:
  adminpw: "{{ config.master_passwd | default('changeme') }}"
  url: "https://{{ config.internet_domain }}/nextcloud"
  mysql_user: nextcloud
  mysql_pass: changeme
  mysql_db: nextcloud

  install_dir: /var/www
  source: "nextcloud-14.0.0.tar.bz2"

#  apps_sources:
#    - "calendar.tar.gz"
#    - "contacts.tar.gz"

  apps_list:
    - "user_ldap"
    - "calendar"
    - "contacts"
    - "mail"
    - "spreed"
