---
#
# Testing dovecot with IMAPS:
#  $ openssl s_client -host localhost -port 993
#  1 login username pass
#  2 LIST "" "*"
#  3 EXAMINE INBOX
#  4 FETCH 1 BODY[]
#  5 logout
#
- name: repositories and packages
  include: packages.yml

- name: configure dovecot
  include: configure.yml

