---
#
# Testing dovecot with IMAPS:
#  $ openssl s_client -host localhost -port 993
#  1 login username pass
#  2 LIST "" "*"
#  3 EXAMINE INBOX
#  4 FETCH 1 BODY[]
#  5 logout
#
# Testing ManageSieve (See: https://doc.dovecot.org/configuration_manual/sieve/, https://doc.dovecot.org/configuration_manual/sieve/managesieve/troubleshooting/, https://datatracker.ietf.org/doc/html/rfc5804.html)
#  $ auth=$(echo -en '\0login\0password' | base64)
#  $ telnet localhost 4190
#  AUTHENTICATE "PLAIN" "$auth"
#  LISTSCRIPTS
#  GETSCRIPT "$scriptname"
#  SETACTIVE "$scriptname"
#  LOGOUT
#

- name: repositories and packages
  include_tasks: packages.yml

- name: configure dovecot
  include_tasks: configure.yml

