---

- name: install dovecot server
  apt:
    state: present
    name:
      - dovecot-core
      - dovecot-ldap
      - dovecot-imapd
      - dovecot-lmtpd
  register: dovecot_install_result

- name: mark dovecot to start on boot
  service: name=dovecot enabled=yes
  when: dovecot_install_result.changed

