---

- name: creating PrivCore config directory - /etc/apache2/privcore-conf
  file: path=/etc/apache2/privcore-conf state=directory owner=root group=root mode=0755

- name: set PHP memory_limit to 512M
  lineinfile: dest=/etc/php/7.4/apache2/php.ini regexp="^memory_limit =" line="memory_limit = 512M"
  notify: restart apache

- name: configuring PHP modules
  template: src={{ item }}.j2 dest=/etc/php/7.4/mods-available/{{ item }}
  with_items:
    - opcache.ini
    - apcu.ini
  notify: restart apache

- name: enabling apache headers module
  command: a2enmod headers
  register: a2enmod_headers
  changed_when: ("Module headers already enabled" not in a2enmod_headers.stdout)
  notify: restart apache

- name: enabling apache rewrite module
  command: a2enmod rewrite
  register: a2enmod_rewrite
  changed_when: ("Module rewrite already enabled" not in a2enmod_rewrite.stdout)
  notify: restart apache

- name: enabling apache ssl module
  command: a2enmod ssl
  register: a2enmod_ssl
  changed_when: ("Module ssl already enabled" not in a2enmod_ssl.stdout)
  notify: restart apache

- name: generating apache default ssl configuration
  template: src=apache-default-ssl.conf.j2 dest=/etc/apache2/sites-available/default-ssl.conf

- name: enabling apache default ssl configuration
  command: a2ensite default-ssl
  register: a2ensite_default_ssl
  changed_when: ("Site default-ssl already enabled" not in a2ensite_default_ssl.stdout)
  notify: reload apache

- name: forcing redirect to SSL in /etc/apache2/sites-available/000-default.conf
  blockinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    block: |

      RewriteCond %{HTTP:X-Forwarded-Proto} !https
      RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,E=nocache:1,NE]

      Header always set Cache-Control "max-age=0, private" env=nocache
      Header always set Expires "-1" env=nocache

      SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on

      IncludeOptional privcore-conf/*.conf

    insertbefore: "</VirtualHost>"
  notify: reload apache

- name: preparing directories
  file: path=/var/www/html/{{ item }} state=directory mode=0755
  with_items:
    - "imgs"
    - "css"

- name: deploying PrivCore welcome page files
  copy: src={{ item }} dest=/var/www/html/{{ item }} force=no
  with_items:
    - "imgs/phpLDAPadmin.png"
    - "imgs/favicon.ico"
    - "imgs/privcore_logo_black2.png"
    - "imgs/nextcloud.png"
    - "imgs/change_password.png"
    - "css/bootstrap.min.css"
    - "css/style.css"

- name: generating PrivCore /var/www/html/index.html file
  template: src=index.html.j2 dest=/var/www/html/index.html

- name: generating PrivCore /var/www/html/ldap_passwd.php file
  template: src=ldap_passwd.php.j2 dest=/var/www/html/ldap_passwd.php

