---

- name: install openldap
  apt:
    state: present
    name:
      - slapd
      - ldap-utils
      - sudo-ldap
      - acl
  register: slapd_install_result

- name: mark slapd to start on boot
  service: name=slapd enabled=yes
  when: slapd_install_result.changed

