---

- name: install packages for all
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - ldap-utils
      - libnss-ldapd
      - libpam-modules
      - libpam-ldapd

- name: install packages for directory servers
  when: ansible_fqdn in groups['openldap']
  apt: name={{ item }} state=present
  with_items:
      - slapd
  notify: 
    - restart ldapd

- name: uninstall LDAP server for machines without role 'openldap'
  when: ansible_fqdn not in groups['openldap']
  apt: name={{ item }} state=absent purge=yes
  with_items:
      - slapd

