---

- name: copy CA certs to /var/www/html/
  tags: openssl_gencerts
  shell: cp {{ssl_config.dir}}/{{ item }} /var/www/html/
  with_items:
    - "certs/ca_cert.der"
    - "certs/ca_crl.pem"

- name: generating apache default ssl configuration
  template: src=apache-default-ssl.conf.j2 dest=/etc/apache2/sites-available/default-ssl.conf

- name: enabling apache ssl module
  command: a2enmod ssl
  register: a2enmod_ssl
  changed_when: ("Module ssl already enabled" not in a2enmod_ssl.stdout)
  notify: restart httpd

- name: enabling apache default ssl configuration
  command: a2ensite default-ssl
  register: a2ensite_default_ssl
  changed_when: ("Site default-ssl already enabled" not in a2ensite_default_ssl.stdout)
  notify: reload httpd

#- name: generating apache OCSP configuration for ocsp.{{ansible_fqdn}}
#  template: src=apache-ocsp-ssl.conf.j2 dest=/etc/apache2/sites-available/ocsp.{{ansible_fqdn}}-ssl.conf
#
#- name: enabling apache OCSP configuration
#  command: a2ensite ocsp.{{ansible_fqdn}}-ssl
#  register: a2ensite_ocsp_ssl
#  changed_when: ("Site ocsp.{{ansible_fqdn}}-ssl already enabled" not in a2ensite_ocsp_ssl.stdout)
#  notify: reload httpd

  # OCSP verification example:
  # openssl ocsp -resp_text -CAfile /etc/ssl/CA/certs/ca_cert.pem -issuer /etc/ssl/CA/certs/ca_cert.pem -cert /etc/ssl/CA/certs/core0.local_cert.pem -url https://ocsp.core0.local

