---

- name: generating root CA key
  command: openssl genrsa -out private/{{openssl_config.local_domain}}_ca_key.pem 4096 chdir={{openssl_config.ca_dir}} creates=private/{{openssl_config.local_domain}}_ca_key.pem

- name: creating root CA certificate
  command: openssl req -config openssl.cnf -key private/{{openssl_config.local_domain}}_ca_key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -subj "/O={{openssl_config.organization_name}}/CN=ROOT CA Certificate" -out certs/{{openssl_config.local_domain}}_ca_cert.pem chdir={{openssl_config.ca_dir}} creates=certs/{{openssl_config.local_domain}}_ca_cert.pem

- name: converting root CA to DER
  command: openssl x509 -outform der -in certs/{{openssl_config.local_domain}}_ca_cert.pem -out certs/{{openssl_config.local_domain}}_ca_cert.der chdir={{openssl_config.ca_dir}} creates=certs/{{openssl_config.local_domain}}_ca_cert.der

