---

- name: install packages
  include_tasks: packages.yml

- name: configure openssl
  include_tasks: configure.yml

- name: creating local CA
  include_tasks: create_ca.yml

- name: generating and signing certificates for machines
  include_tasks: generate_certs.yml

- name: setting mode to 0440 for private keys
  file: path={{openssl_config.ca_dir}}/private/ owner=root group=root mode=0440 recurse=yes

- name: setting mode to 0710 for private keys directory
  file: path={{openssl_config.ca_dir}}/private owner=root group=root mode=0710

- name: deploying generated certificates
  include_tasks: deploy_certs.yml

