---

- name: install packages
  include: packages.yml

- name: configure openssl
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_gencerts
  include: configure_openssl.yml

- name: creating local CA
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_gencerts
  include: create_ca.yml

- name: generating and signing certificates for machines
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_gencerts
  include: generate_certs.yml

- name: setting mode to 0600 for private keys
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_gencerts
  file: path={{ssl_config.dir}}/private/  owner=root group=root mode=0600 recurse=yes

- name: setting mode to 0711 for private keys directory
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_gencerts
  file: path={{ssl_config.dir}}/private  owner=root group=root mode=0711

- name: deploying certificates to machines
  tags: openssl_gencerts
  synchronize: src={{ssl_config.dir}}/{{ item }} dest=/etc/ssl/{{ item }}
  with_items:
    - 'certs/ca_cert.pem'
    - 'certs/{{ansible_fqdn}}_cert.pem'
    - 'private/{{ansible_fqdn}}_key.pem'
  delegate_to: "{{ groups['openssl_ca'][0] }}"

- name: configure apache
  when: ansible_fqdn in groups['openssl_ca']
  tags: openssl_apache
  include: configure_apache.yml

