---

- name: install packages for all
  apt: name={{ item }} state=present force=yes
  with_items:
      - openssl

- name: install packages for CA Server
  when: ansible_fqdn in groups['openssl_ca']
  apt: name={{ item }} state=present force=yes update_cache=yes
  with_items:
      - rsync     # rsync for ansible synchronize module
      - apache2
  notify: 
    - restart httpd

