---

- name: Using configured resolvers
  when: dns_config.nameservers | length > 0
  set_fact: _nameservers="{{ dns_config.nameservers }}"

- name: Preparing default resolvers list
  when: dns_config.nameservers | length == 0
  set_fact: _default_nameservers="{{ _default_nameservers|default([]) + [ hostvars[item].default_ipv4_address ] }}"
  with_items: "{{ groups['bind_master'] + groups['bind_slave'] }}"

- name: Using default resolvers
  when: dns_config.nameservers | length == 0
  set_fact: _nameservers="{{ _default_nameservers }}"

- name: generating /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  register: _resolv_conf

- block:
    - name: looking up for active NetworkManager connections
      shell: nmcli -t -f UUID,DEVICE connection show --active
      register: _nmcli_conn

    - set_fact:
        nmcli_conn: "{{ nmcli_conn|default([]) + [{ 'uuid': item.split(':')[0], 'dev': item.split(':')[1] }] }}"
      with_items: "{{ _nmcli_conn.stdout_lines }}"

    - name: reconfiguring NetworkManager dns settings
      shell: nmcli con modify {{ item.uuid }} ipv4.dns '{{ _nameservers | join( " " )}}'
      with_items: "{{ nmcli_conn | default( {} ) }}"
      when: ansible_default_ipv4.interface == item.dev

  when: _resolv_conf.changed

