---

- name: creating directory /etc/bind/masters
  file: path=/etc/bind/masters state=directory owner=root group=root mode=0755

- name: generating default zone /etc/bind/masters/{{ansible_domain}}
  template: src=zone.j2 dest=/etc/bind/masters/{{ansible_domain}}
  notify: reload named

- name: resolving default reverse zone name as "{{ ansible_default_ipv4.address.split('.')[2] }}.{{ ansible_default_ipv4.address.split('.')[1] }}.{{ ansible_default_ipv4.address.split('.')[0] }}.in-addr.arpa"
  tags: bind_configure
  set_fact:
    default_rev_domain: "{{ ansible_default_ipv4.address.split('.')[2] }}.{{ ansible_default_ipv4.address.split('.')[1] }}.{{ ansible_default_ipv4.address.split('.')[0] }}.in-addr.arpa"

- name: generating default reverse zone /etc/bind/masters/{{default_rev_domain}}
  template: src=zone-in-addr.arpa.j2 dest=/etc/bind/masters/{{default_rev_domain}}
  notify: reload named

- name: adding local master zones definitions to /etc/bind/named.conf.local
  blockinfile:
    dest: /etc/bind/named.conf.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    block: |

      zone "{{ansible_domain}}" { type master; file "/etc/bind/masters/{{ansible_domain}}"; };
      zone "{{default_rev_domain}}" { type master; file "/etc/bind/masters/{{default_rev_domain}}"; };

  notify: reload named

