---

- name: install packages
  apt:
    state: present
    name:
      - bind9
#      - bind9-dyndb-ldap # https://pagure.io/bind-dyndb-ldap https://blogs.mindspew-age.com/2013/06/07/bind-dns-openldap-mdb-dynamic-domainsub-domain-configuration-of-dns/
  register: bind9_install_result

- name: mark bind9 to start on boot
  service: name=bind9 enabled=yes
  when: bind9_install_result.changed

