---

- name: creating database {{roundcube_config.mysql_db}}
  mysql_db: name={{roundcube_config.mysql_db}} state=import target=/usr/share/roundcube/SQL/mysql.initial.sql

- name: creating user {{roundcube_config.mysql_user}}@localhost with full access to {{roundcube_config.mysql_db}} database
  mysql_user: name={{roundcube_config.mysql_user}} host=localhost password={{roundcube_config.mysql_pass}} priv={{roundcube_config.mysql_db}}.*:ALL state=present

- name: reconfiguring /etc/roundcube/apache.conf
  lineinfile: dest=/etc/roundcube/apache.conf regexp="Alias " line="    Alias /roundcube /var/lib/roundcube"
  notify:
    - reload httpd

- name: generating new DES key
  shell: pwgen -s 24 -N 1
  changed_when: false
  register: _roundcube_des_key

- name: creating variable roundcube_des_key
  set_fact:
    roundcube_des_key: "{{_roundcube_des_key.stdout_lines[0]}}"

- name: generating roundcube configuration files
  template: src={{item}}.j2 dest=/etc/roundcube/{{item}}
  with_items:
    - 'config.inc.php'
    - 'debian-db.php'

  # git clone https://github.com/blind-coder/rcmcarddav.git
  # git clone https://github.com/priyadi/roundcube-converse.js-xmpp-plugin
- name: deploying roundcube plugins
  synchronize: src={{item.src}}/ dest=/var/lib/roundcube/plugins/{{item.dest}} recursive=yes
  with_items:
    - { src: 'rcmcarddav', dest: 'carddav' }
    - { src: 'roundcube-converse.js-xmpp-plugin', dest: 'converse' }

- name: installing rcmcarddav plugin dependencies
  shell: |
    cd /var/lib/roundcube/plugins/carddav
    curl -sS https://getcomposer.org/installer | php
    php composer.phar install
  args:
    executable: /bin/bash
  register: roundcube_carddav_composer
  changed_when: ("Nothing to install or update" not in roundcube_carddav_composer.stdout)

- name: generating roundcube plugins configuration files
  template: src={{item}}.j2 dest=/var/lib/roundcube/plugins/{{item}}
  with_items:
    - 'carddav/config.inc.php'
    - 'converse/config.inc.php'

