---

- name: install roundcube webmail client
  when: ansible_fqdn in groups['roundcube']
  apt: name={{ item }} state=present force=yes update_cache=yes
  with_items:
      - python-mysqldb  # for ansible mysql_user module
      - roundcube
      - roundcube-mysql
      - php5-curl       # carddav plugin dependency
      - pwgen           # used for DES keys generation

- name: install roundcube webmail client for machines without role 'roundcube'
  when: ansible_fqdn not in groups['roundcube']
  apt: name={{ item }} state=absent purge=yes force=yes
  with_items:
      - python-mysqldb  # for ansible mysql_user module
      - roundcube
      - roundcube-mysql

