---

- name: Generating /etc/phpldapadmin/config.php
  template: src=phpldapadmin_config.php.j2 dest=/etc/phpldapadmin/config.php group=www-data mode=0640

- name: Generating /etc/phpldapadmin/apache.conf
  template: src=apache.conf.j2 dest=/etc/phpldapadmin/apache.conf
  notify:
    - reload apache

- name: linking to phpldapadmin apache configuration
  file: src=/etc/phpldapadmin/apache.conf dest=/etc/apache2/conf-available/phpldapadmin.conf state=link force=yes

- name: enabling apache phpldapadmin.conf
  command: a2enconf phpldapadmin
  register: a2enconf_phpldapadmin
  changed_when: ("Conf phpldapadmin already enabled" not in a2enconf_phpldapadmin.stdout)
  notify:
    - reload apache

