---

- name: Generating /etc/phpldapadmin/config.php
  template: src=phpldapadmin_config.php.j2 dest=/etc/phpldapadmin/config.php

- name: Generating /etc/apache2/conf-available/phpldapadmin.conf
  template: src=apache.conf.j2 dest=/etc/apache2/conf-available/phpldapadmin.conf
  notify:
    - reload httpd

- name: enabling apache phpldapadmin.conf
  command: a2enconf phpldapadmin
  register: a2enconf_phpldapadmin
  changed_when: ("Conf phpldapadmin already enabled" not in a2enconf_phpldapadmin.stdout)
  notify:
    - reload httpd

