---

- name: install packages for phpldapadmin service
  apt:
    state: present
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-ldap
      - php-xml
      - php-cli
      - unzip # needed by unarchive ansible module
  notify:
    - restart apache

- name: unarchive source files
  unarchive: src={{ item.src }} dest={{ item.dest }} keep_newer=yes
  with_items: "{{ phpldapadmin_config.sources }}"

- name: linking
  file: src=/var/www/phpLDAPadmin-1.2.5 dest=/var/www/phpldapadmin state=link owner=root group=root force=yes

