---

- name: install packages for phpldapadmin service
  when: ansible_fqdn in groups['openldap']
  apt: name={{ item }} state=present force=yes
  with_items:
      - apache2
      - libapache2-mod-php
      - php-ldap
      - php-cli
  notify: 
    - restart httpd

- name: copying custom packages
  copy: src={{ item }} dest=/var/cache/apt/archives/
  with_items: "{{phpldapadmin_config.packages}}"

- name: installing custom phpldapadmin packages
  command: dpkg -i /var/cache/apt/archives/{{ item }}
  with_items: "{{phpldapadmin_config.packages}}"
  register: ldapadmn_install_result
  failed_when: ldapadmn_install_result.rc != 0
  changed_when: ldapadmn_install_result.rc != 0

#- name: install phpldapadmin files
#  when: ansible_fqdn in groups['openldap']
#  unarchive: src={{ phpldapadmin_config.source }} dest={{ phpldapadmin_config.install_dir }} keep_newer=yes
#
#- name: Applying patches
#  patch: src=php5.5-compatibility.patch basedir={{ phpldapadmin_config.install_dir }}/phpldapadmin strip=1

- name: uninstall phpldapadmin for machines without role 'openldap'
  when: ansible_fqdn not in groups['openldap']
  apt: name={{ item }} state=absent purge=yes force=yes
  with_items:
      - php-ldap
      - phpldapadmin
  notify: 
    - restart httpd

