---

#
# Auth test:
#   $ user=$(echo -n "username" | base64)
#   $ pass=$(echo -n "pass" | base64)
#   $ openssl s_client -host example.com -port 465
#   EHLO example.com
#   AUTH LOGIN
#   $user
#   $pass
#
# Display configuration:
#   # exim -bP
#
# Verify configuration:
#   # exim4 -bV
#
# Debug routing:
#   $ exim -bt user@domain
#
# Debug exim lookups
#   $ exim -bt -d+lookup user@domain
#
# Deliver message:
#   $ exim -M id

- name: repositories and packages
  include_tasks: packages.yml

- name: configure exim
  include_tasks: configure.yml

