---

owncloud_config:
  adminpw: "{{ config.master_passwd | default('changeme') }}"
  url: "https://{{ config.internet_domain }}/owncloud"
  mysql_user: owncloud
  mysql_pass: changeme
  mysql_db: owncloud

