---

- name: generating privcore global bash profile /etc/profile.d/privcore_profile.sh
  template: src=privcore_profile.sh.j2 dest=/etc/profile.d/privcore_profile.sh

- name: enable and start chronyd service
  service: name=chronyd state=started enabled=yes

