---

exim_config:

  internet_domain: "{{ config.internet_domain }}"
  smtp_internet_domains: "{{ config.smtp_internet_domains }}"
  local_domain: "{{ config.local_domain }}"

  ldap_server_uri: "{{ config.ldap_server_uri }}"
  suffix: "{{ config.suffix }}"

  ro_user_dn: "{{ config.ro_user_dn }}"
  ro_user_pw: "{{ config.ro_user_passwd }}"

  tls_ca_cert: "{{ config.tls_ca_cert }}"
  tls_cert: "{{ config.tls_cert }}"
  tls_cert_key: "{{ config.tls_cert_key }}"

  # Enable greylist mail delay for senders unforseen before
  greylist_new_senders: "{{ config.smtp_greylist_new_senders | default(false) }}"

  # Check $spool_directory location with: exim -bP | grep ^spool_directory
  greylist_dbfile: "/var/spool/exim4/greylist.sqlite"
  # For how long (in seconds) email will be delayed
  grelist_delay: 300

