---
#
# Documentation: https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html
#

- name: creating database {{nextcloud_config.mysql_db}}
  mysql_db: name={{nextcloud_config.mysql_db}} state=present

- name: creating user {{nextcloud_config.mysql_user}}@localhost with full access to {{nextcloud_config.mysql_db}} database
  mysql_user: name={{nextcloud_config.mysql_user}} host=localhost password={{nextcloud_config.mysql_pass}} priv={{nextcloud_config.mysql_db}}.*:ALL state=present

- name: resetting files ownerships and permissions
  file: path={{ nextcloud_config.install_dir }}/nextcloud owner=www-data group=www-data mode=0750 recurse=yes

- name: configuring
  shell: |
    su - www-data -s /bin/bash -c ' \
    cd {{ nextcloud_config.install_dir }}/nextcloud && \
    php occ maintenance:install --no-interaction --database="mysql" \
      --database-name="{{nextcloud_config.mysql_db}}" \
      --database-user="{{nextcloud_config.mysql_user}}" \
      --database-pass="{{nextcloud_config.mysql_pass}}" \
      --admin-user="admin" --admin-pass="{{nextcloud_config.master_passwd}}" \
      --data-dir="{{ nextcloud_config.install_dir }}/nextcloud/data" && \
    php occ db:add-missing-indices && \
    php occ background:cron && \
    php occ config:system:set overwrite.cli.url --type=string --value="https://{{ nextcloud_config.internet_domain }}" && \
    php occ config:system:set memcache.local --type=string --value="\OC\Memcache\APCu" && \
    php occ config:system:set default_phone_region --type=string --value="{{ nextcloud_config.country_code }}" && \
    php occ config:system:set trusted_domains 0 --type=string --value="{{ nextcloud_config.internet_domain }}" && \
    php occ config:system:set trusted_domains 1 --type=string --value="{{ inventory_hostname }}" && \
    php occ config:system:set maintenance_window_start --type=integer --value=3 && \
    php occ config:system:set mail_smtpmode --type=string --value=sendmail && \
    php occ config:system:set mail_sendmailmode --type=string --value=pipe && \
    php occ config:system:set mail_domain --type=string --value="{{ nextcloud_config.smtp_internet_domains[0] }}" && \
    php occ config:system:set mail_from_address --type=string --value=admin && \
    php occ user:setting admin settings email "{{ nextcloud_config.admin_user }}@{{ nextcloud_config.smtp_internet_domains[0] }}"
    '
    :
  register: occ_install_result
  failed_when: occ_install_result.rc != 0
  changed_when: occ_install_result.rc != 0
# become_flags seems not working properly with mitogen plugin
#  become: true
#  become_method: su
#  become_user: www-data
#  become_flags: '-s /bin/bash'

- name: enabling and installing basic apps
  shell: |
    su - www-data -s /bin/bash -c ' \
    cd {{ nextcloud_config.install_dir }}/nextcloud && \
    php occ app:install --no-interaction --quiet {{ item }} && \
    php occ app:enable --no-interaction --quiet {{ item }}
    '
    :
  with_items: "{{ nextcloud_config.apps_list }}"
  register: occ_app_result
  failed_when: occ_app_result.rc != 0
  changed_when: occ_app_result.rc != 0
# become_flags Seems not working properly with mitogen plugin
#  become: true
#  become_method: su
#  become_user: www-data
#  become_flags: '-s /bin/bash'
#
- name: configuring basic apps
  shell: |
    su - www-data -s /bin/bash -c ' \
    cd {{ nextcloud_config.install_dir }}/nextcloud && \
    {% for config in nextcloud_config.apps_config %}
    php occ config:app:set --update-only --quiet {{ config.app }} {{ config.key }} --value "{{ config.value }}" && \
    {% endfor %}
    :
    '
    :
  register: occ_app_result
  failed_when: occ_app_result.rc != 0
  changed_when: occ_app_result.rc != 0

- name: hashing LDAP user password with BASE64
  shell: echo -n "{{nextcloud_config.ro_user_pw}}" | base64
  changed_when: false
  register: _ldap_userpw_base64

- name: creating variable ldap_userpw_base64
  set_fact:
    ldap_userpw_base64: "{{_ldap_userpw_base64.stdout_lines[0]}}"

- name: Generating apps settings file to /tmp/nextcloud.mysql
  template: src=nextcloud.mysql.j2 dest=/tmp/nextcloud.mysql mode=0400

- name: importing configuration from /tmp/nextcloud.mysql
  shell: |
    mysql --force {{nextcloud_config.mysql_db}} < /tmp/nextcloud.mysql
  args:
    executable: /bin/bash

- name: enabling apache headers module
  command: a2enmod headers
  register: a2enmod_headers
  changed_when: ("Module headers already enabled" not in a2enmod_headers.stdout)
  notify: restart apache

- name: enabling apache rewrite module
  command: a2enmod rewrite
  register: a2enmod_rewrite
  changed_when: ("Module rewrite already enabled" not in a2enmod_rewrite.stdout)
  notify: restart apache

- name: enabling apache proxy module
  command: a2enmod proxy
  register: a2enmod_proxy
  changed_when: ("Module proxy already enabled" not in a2enmod_proxy.stdout)
  notify: restart apache

- name: enabling apache proxy_http module
  command: a2enmod proxy_http
  register: a2enmod_proxy_http
  changed_when: ("Module proxy_http already enabled" not in a2enmod_proxy_http.stdout)
  notify: restart apache

- name: generating apache configuration for Nextcloud
  template: src=nextcloud.apache.j2 dest=/etc/apache2/conf-available/nextcloud.conf
  notify: reload apache

- name: generating apache configuration for LibreOffice Online
  template: src=lool.apache.j2 dest=/etc/apache2/privcore-conf/lool.conf
  notify: reload apache

- name: enabling apache configuration for Nextcloud
  command: a2enconf nextcloud
  register: a2enconf_nextcloud
  changed_when: ("Conf nextcloud already enabled" not in a2enconf_nextcloud.stdout)
  notify: reload apache

- name: generating nextcloud cron configuration
  template: src=nextcloud.cron.j2 dest=/etc/cron.d/nextcloud

