---

#
# After copying new files to users data folder rescan files:
#
# # su - www-data -s /bin/bash -c 'cd /var/www/nextcloud; php occ files:scan --all'
#

- name: repositories and packages
  include: packages.yml

- name: configure coturn server and set fact coturn_auth_secret
  include: coturn.yml

- name: configure nextcloud
  include: configure.yml

