---

- name: install nextcloud dependencies
  apt:
    state: present
    name:
      - python3-mysqldb  # for ansible mysql_user module
      - libapache2-mod-php # module for apache
      - php
      - php-cli
      - php-apcu
      # ICE/TURN/STUN server
      - coturn
      # nextcloud dependencies
      - fonts-font-awesome
      - fonts-liberation
      - fonts-linuxlibertine
      - fonts-lohit-deva
      - fonts-sil-gentium-basic
      - fonts-wqy-microhei
      - libjs-chosen
      - libjs-jquery-mousewheel
      - libjs-jquery-timepicker
      - libjs-mediaelement
      - libjs-underscore
      - libphp-phpmailer
      - php-common
      - php-curl
      - php-gd
      - php-json
      - php-xml
      - php-mbstring
      - php-zip
      - php-mysql
      - php-bz2
      - php-intl
      # ldap support
      - php-ldap
      # external user authentication
      - php-imap
      # passwordless login
      - php-bcmath
      - php-gmp
      # preview generation
      - imagemagick
      - php-imagick
      - ffmpeg

- name: creating _nc_archive_file variable
  set_fact:
    _nc_archive_file: "nextcloud-{{ nextcloud_config.version}}.tar.bz2"

- name: Download nextcloud archive
  get_url:
    url: https://download.nextcloud.com/server/releases/{{ _nc_archive_file }}
    dest: /tmp/{{ _nc_archive_file }}
    mode: '0440'
    checksum: '{{ nextcloud_config.archive_checksum }}'

- name: install nextcloud files
  unarchive: remote_src=yes src=/tmp/{{ _nc_archive_file }} dest={{ nextcloud_config.install_dir }} keep_newer=yes

# For those it's better to deploy known good versions than install it with "php -f occ app:install ..."
#- name: install nextcloud apps from sources
#  unarchive: src={{ item }} dest={{ nextcloud_config.install_dir }}/nextcloud/apps keep_newer=yes
#  with_items: "{{ nextcloud_config.apps_sources }}"

- name: resetting files ownerships and permissions
  file: path={{ nextcloud_config.install_dir }}/nextcloud owner=www-data group=www-data mode=0750 recurse=yes

