---

- name: install nextcloud dependencies
  when: ansible_fqdn in groups['nextcloud']
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - python-mysqldb  # for ansible mysql_user module
      - libapache2-mod-php # module for apache
      - php
      - php-apcu
      # ICE/TURN/STUN server
      - coturn
      # nextcloud dependencies
      - fonts-font-awesome
      - fonts-liberation
      - fonts-linuxlibertine
      - fonts-lohit-deva
      - fonts-sil-gentium-basic
      - fonts-wqy-microhei
      - libjs-chosen
      - libjs-jquery-mousewheel
      - libjs-jquery-timepicker
      - libjs-mediaelement
      - libjs-pdf
      - libjs-underscore
      - libphp-phpmailer
      - php-doctrine-dbal
      - php-getid3
      - php-patchwork-utf8
      - php-pear
      - php-pimple
      - php-sabre-dav
      - php-seclib
      - php-symfony-class-loader
      - php-symfony-console
      - php-symfony-routing
      - php-cli
      - php-gd
      - php-json
      - php-mcrypt
      - php-curl
      - php-intl
#      - php-mysql
      - php-mysqlnd
      - php-zip

- name: install nextcloud files
  when: ansible_fqdn in groups['nextcloud']
  unarchive: src={{ nextcloud_config.source }} dest={{ nextcloud_config.install_dir }} keep_newer=yes

# For those it's better to deploy known good versions than install it with "php -f occ app:install ..."
#- name: install nextcloud apps from sources
#  when: ansible_fqdn in groups['nextcloud']
#  unarchive: src={{ item }} dest={{ nextcloud_config.install_dir }}/nextcloud/apps keep_newer=yes
#  with_items: "{{ nextcloud_config.apps_sources }}"

- name: resetting files ownerships and permissions
  when: ansible_fqdn in groups['nextcloud']
  file: path={{ nextcloud_config.install_dir }}/nextcloud owner=www-data group=www-data mode=0755 recurse=yes

- name: uninstall nextcloud dependencies for machines without role 'nextcloud'
  when: ansible_fqdn not in groups['nextcloud']
  apt: name={{ item }} state=absent purge=yes
  with_items:
      - python-mysqldb

