---

- name: PrivCore common configuration setup
  hosts: all
  gather_facts: yes
  roles:
    - { role: privcore_config, tags: always }

- name: Domain controller
  hosts: controller
  gather_facts: yes
  roles:
    - { role: openssl, tags: openssl }
    - { role: openldap, tags: openldap }
    - { role: bind, tags: bind }

- name: Join all machines to the domain controller
  hosts: all
  gather_facts: yes
  roles:
    - { role: nameservers, tags: nameservers }
    - { role: sssd, tags: sssd }

- name: Aplication server
  hosts: app
  gather_facts: yes
  roles:
    # Basic apache configuration
    - { role: apache, tags: apache }
    # LDAP management interface
    - { role: phpldapadmin, tags: phpldapadmin }
    # Collaboration server (file, contacts, calendar)
    - { role: nextcloud, tags: nextcloud }

- name: Mailboxes and SMTP relay server
  hosts: mail
  gather_facts: yes
  roles:
    - { role: dovecot, tags: dovecot }
    - { role: exim, tags: exim }

