---

- name: privcore
  hosts:
    - all
  gather_facts: yes

  roles:
    - { role: openssl, tags: ssl } # create CA and generate certificates for machines and its services
    - { role: bind, tags: dns } # local DNS server
    - { role: openldap, tags: ldap } # initialize directory servers and assign hosts to it
    - { role: phpldapadmin, tags: phpldapadmin } # LDAP management interface
    - { role: nextcloud, tags: cloud } # sharing server (file, contacts, calendar)
    - { role: dovecot, tags: imap } # E-mail mailboxes
    - { role: exim, tags: smtp } # E-mail transport
    - { role: privcore, tags: privcore } # Some privcore specific configuration

    # Obsolete and unsupported
    - { role: prosody, tags: xmpp } # prosody XMPP/Jabber server
    - { role: roundcube, tags: webmail } # E-mail webclient
