---
#
# Please read:
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/sssd#sssd-overview-how
#

- name: repositories and packages
  include: packages.yml

- name: configure sssd
  include: configure.yml

- name: Generating LDAP client config /etc/ldap/ldap.conf
  template: src=ldap.conf.j2 dest=/etc/ldap/ldap.conf

